### ISSUE TITLE
болтливость системы

### ISSUE THREAD

**Issue by netman1ac** [Aculeasis/mdmTerminal2#1]
Можно ли сделать настройку на болтание системы?
В первом терминале был ding и сразу можно было говорить,
а тут она здоровается привет-приветами что немного раздражает так как получается задержка 
я могу изменить локально, но тогда придется не обновляться или форкать, что очень не хочется.

Почему то чувствительность, ниже чем у первого mdmpiterminal
На ключевую фразу реагирует так же, но вот голос потом слышит хуже и почти постоянно говорит "не поняла".

Еще одно странное поведение:
От мжд приходит сообщение с "важностью" 10 и терминал его проговаривает, но минимальный уровень проговаривания в мжд стоит 30.
Т.е. игнорируется уровень важности и терминал болтает всё что должен и что не должен.
Не знаю, может это "фишка" мжд отправки в терминал или ошибка скрипта mdmterminal2

**Comment by Aculeasis** [comment]
Опцию добавлю.

Хуже распознает голос если говорить вместе с терминалом или всегда? Если всегда то наверное это из-за того что настройка `energy_threshold` начинается параллельно с проигрыванием динга. Я это уберу. Если не поможет то можно вернуть опционально старый, блокирующий, режим когда распознавание начинается после произнесения фразы. У меня проблемы с распознаванием только когда вместе с терминалом говорю.

Это фишка мжд, он просто присылает tts: и фразу.

**Comment by netman1ac** [comment]
Я жду 1-2 секунды пока скрипт договорит привет-привет и после говорю любую фразу.
И после этого слышу "ничего не слышно повторите ваш запрос", на повторный запрос распознает чуть лучше, но все же не всегда

**Comment by netman1ac** [comment]
c no_hello = 1 распознает лучше, спасибо

**Comment by netman1ac** [comment]
Еще проблему нашел. Скрипт слышит еще и "Сигнал перед сообщением:", записывает и отправляет его как голос и поэтому не слышит тебя.

У меня терминал стоит на той же малине где мжд. тут или не отправлять сообщение в терминал и говорить встроенным яндексом(который работает медленней чем скрипт) или использовать терминал и отключить яндекс, но тогда болтает всё.
Сейчас почему то сломался синтез. говорит ошибка синтеза речи, но модуль яндекса в мжд отлично работает с этим ключом.

**Comment by Aculeasis** [comment]
Какая именно ошибка синтеза? И что приходит от мжд `Server: Получены данные`?

**Comment by Aculeasis** [comment]
> Еще проблему нашел. Скрипт слышит еще и "Сигнал перед сообщением:", записывает и отправляет его как голос и поэтому не слышит тебя.

Его можно отключить, `alarmtts = 0`.  С `blocking_listener` hello и сигналы не будут записываться.

> там появилась новая настройка 'может принимать уведомления от системы'

У меня такого нет. Это в альфе?

**Comment by netman1ac** [comment]
Да, это в альфе, но я окатился на стабильную так как много чего отломалось, а тестировать пока некогда.

alarmtts сразу же поставил 1. 
Малина все равно начинает слушать где то через 1-2 секунды (там опция еще стоит в коде слушать шум секунду) и пропускает фразы типа "алиса(активация) открой кран" 
из этого всего она в лучшем случае успевает услышать только "кран".

Еще одна просьба. 
Можно ли вытащить в настройки 'phrase_time_limit'? Очень уж долго ждет временами
Дефолтно поставить её в 10-15 сек, но дать пользователю выбирать.
В старом я еще вроде время "не ответа подкручивал", но это уже будет лишним

**Comment by Aculeasis** [comment]
Совсем убирать `adjust_for_ambient_noise` нельзя, он настраивает чувствительность микрофона. 
Можно вынести `energy_threshold` в конфиг и если он задан не слушать шум, тогда мб будет без разрывно. Если не задана принтить его в лог. Но адаптивности не будет.

`phrase_time_limit` вынесу.

**Comment by netman1ac** [comment]
Я игрался раньше с energy_threshold
Если его отключить то плохо распознает голос при фоновом шуме и скорости малине не добавляет.
Может еще определиться с полезностью настроек и безопасные для пользователя вынести в php модуль мжд?

**Comment by Aculeasis** [comment]
Тогда модуль станет не совместим с первой версией терминала (настройки есть а не работают), жаль что мжд не запрашивает идентификацию у терминалов.
Ну и кто-то должен их туда внести.

**Comment by netman1ac** [comment]
Насчет id можно попросить допилить мжд, я бы еще попросил бы сделать передачу "важности" терминалу.
Насчет настроек 
можно подписывать что эти настройки совместимы только с V2
