### ISSUE TITLE
Передача настроек

### ISSUE THREAD

**Issue by lanket** [Aculeasis/mdmTerminal2#10]
В связи с невозможностью вовремя дорабатывать модуль для Мажордома, а также для универсальности для других контроллеров и исключения несогласованности передачи настроект от модуля контроллера Предлагаю:
Чтобы модуль контоллера и терминал имели одну и туже структуру и набор настроек по запросу от контроллера через сокет "get_settings" отдавать json структуры settins.ini в таком формате:

`
{
   "Наименование вкладки в HTML интерфейсе": {
       "Наименование секции настроек например settings": {
		       "Переменная например providertts": {
		       		"namehtml": "Наименование для интерфейса в данном случае : провайдер синтеза речи",
		       		"deschtml": 'Описание переменной для интерфейса в данном случае : Провайдер синтеза речи <br> google - Ключ не нужен, голос так себе. <br> yandex - cм. [yandex] <br> aws - Polly от AWS. Нужен аккаунт AWS.<br> azure - MS Azure, см. [azure] <br> rhvoice, rhvoice-rest - "локальные провайдеры". См. соответствующие секции.',
		       		"type": "checkbox / text / select",
		       		"namehtml": "Наименование для интерфейса в данном случае : провайдер синтеза речи",
		       		"default": "Значение по умолчанию",
		       		"options": [
		       				"массив значений",
		       				"в случе",
		       				"если type=select",
		       				"например переменная providertts",
		       		],
		       },
       },
   },
}
`

**Comment by Aculeasis** [comment]
Да, можно сделать такое.

**Comment by lanket** [comment]
[ТЗ](https://jsoneditoronline.org/?id=8628154c8cf74e8da978ed63002a191d)
[V1](https://jsoneditoronline.org/?id=a90d2a37040d44e382e58daaed1f724d)

**Comment by lanket** [comment]
Добавь пожалуйста в этот json по каждой опции помимо name, desc, default и type еще и value 
там должно быть текущее значение переменной

**Comment by Aculeasis** [comment]
Думаешь стоит? Там же никакой безопасности - любой может подключиться и скачать настройки.

**Comment by lanket** [comment]
Также можно подключиться к вебинтерфейсу самого терминала и также увидить все настройких или тупо сохранить данные формы.
Я просто хочу уйти от хранения настроек в базе МЖД.
Так как терминал постоянно обастает дополнительными настройками, а чего еще хуже иногда тип данных.

Ну или тогда раз тут кардинально меняю код модуля,  то заодно и можно будет добавить авторизацию по токену. При первомобащении его сгенерить и передать терминалу и тогда со стороны подключиться не получиться. Так же надежно получается? Все таки не для банка софт пишем.

Собственно алгоритм простой хочу сделать.  Модуль скачивает этот JSON и генерит интерфейс с формами под текущую версию терминала с актуальными настройками.

**Comment by Aculeasis** [comment]
> Также можно подключиться к вебинтерфейсу самого терминала и также увидить все настройких или тупо сохранить данные формы.

Не совсем - вебинтерфейс еще надо поставить + при первом запуске он запросит и установит логин-пароль, тут все на ответственности пользователя.

> При первомобащении его сгенерить и передать терминалу и тогда со стороны подключиться не получиться. Так же надежно получается?

Думаю да. Тогда я добавлю требование авторизации для remote_log, settings и удалю ws_token. Желательно чтобы все команды от модуля шли с авторизацией, в принципе её можно кидать до команд и не ждать подтверждения (хотя лучше и проверять ответ, на случай если токены не совпали - можно кинуть авторизацию с командами а потом проверить ответ авторизации Ж).
Еще надо будет код js поправить - сделать авторизацию логгера, как в web-config, и убрать ws_token.

**Comment by Aculeasis** [comment]
Добавил в [dev](https://github.com/Aculeasis/mdmTerminal2/tree/dev).
