### ISSUE TITLE
Предлагаю рассмотреть проект VOSK  в качестве замены snowboy

### ISSUE THREAD

**Issue by Peter-Idea** [Aculeasis/mdmTerminal2#11]
Добрый день.
Недавно заметил появление проекта VOSK 
([https://alphacephei.com/ru/](https://alphacephei.com/ru/)
[https://alphacephei.com/vosk/index.ru.html](https://alphacephei.com/vosk/index.ru.html))

Возможно он подойдет для замены snowboy.

VOSK — это инновационная библиотека нового поколения для распознавания речи с открытым кодом. 
Распознавание речи с библиотекой VOSK не требует подключения к сети и передачи данных. [Установка и использование](https://github.com/alphacep/vosk-api).

Для теста развернул на OPPC+ под управлением ARMBIAN, установка оказалась не сложной.
После включения микрофона vosk стал распознавать. Испытания распознавания с микрофона на скрипте из [проекта](https://github.com/alphacep/vosk-api/blob/master/python/example/test_microphone.py)  прошли успешно.
Мне показалась длительным время между произношением и выводом готового результата. Однако в сравнении с pocketsphinx vosk субъективно выигрывает.

Пока не нашел как в нем сделать распознавание по ключевому слову.

**Comment by Aculeasis** [comment]
VOSK просто речь распознает, по сравнению с snowboy он жрет много ресурсов причем постоянно. На слабых Orange Pi это не вариант.
Я сделал плагин использующий vosk-server в качестве hwd ([mdmt2-streams-hwd](https://github.com/Aculeasis/mdmt2-streams-hwd)), но сервер надо запускать на быстром железе в локалке. Хотя работает хорошо и модели делать не надо.

**Comment by Peter-Idea** [comment]
@Aculeasis, спасибо за ответ. Тикет закрываю.
