### ISSUE TITLE
Задержка около 9 минут после уведомления

### ISSUE THREAD

**Issue by Garkus98** [Aculeasis/mdmTerminal2#13]
Скажите пожалуйста почему есть постоянная задержка между тем когда пришло уведомление в majordomo и оно его сказало. При чем задержка на всех абсолютно уведомлениях. И генерация ответа голосового тоже через 9 минут по логам.

**Comment by Garkus98** [comment]
![Screenshot 2020-12-24 100719](https://user-images.githubusercontent.com/76440047/103069167-d50edd00-45cf-11eb-9408-2b75beb6e0a1.jpg)

**Comment by Aculeasis** [comment]
По логу задержка 9 секунд, но это все равно очень много. Не знаю почему так, попробуйте включить в настройках `[settings] no_background_play = on` и покажите логи.  Например у меня это происходит так (задержка 102 мс):
```bash
2020.12.26 10:51:01.222 Server: Received data: 'tts:10 часов 51 минута'
2020.12.26 10:51:01.223 Player: low say '10 часов 51 минута' pause 0
2020.12.26 10:51:01.226 TTS: say '10 часов 51 минута' 
2020.12.26 10:51:01.324 Player: Играю /root/mdmTerminal2/src/resources/dong.wav ...
2020.12.26 10:51:01.363 TTS: сгенерированно rhvoice-rest за 138.29 ms [reply:96.5 ms, diff:41.79 ms]: /root/mdmTerminal2/src/tts_cache/rhvoice-rest_7253bb687da593eb14809b6517b155c9ff2f6cb3.mp3
```

**Comment by Garkus98** [comment]
у меня яндекс идеально работает

**Comment by Garkus98** [comment]
![Screenshot 2020-12-26 122724](https://user-images.githubusercontent.com/76440047/103148896-bb0eff00-4775-11eb-9e2d-7db6bf01e623.jpg)
таже самая задержка после вашего совета

**Comment by Aculeasis** [comment]
Вот тут нет задержки, получил сообщение и через 84 мс стал его озвучивать. А то что оно на 9 минут опоздало это наверное мжд с задержкой присылает. Что выше по логу где `Server: Allow new connection`?

**Comment by Garkus98** [comment]
![Screenshot 2020-12-27 092248](https://user-images.githubusercontent.com/76440047/103165154-1fd56280-4825-11eb-89ea-9a91a1c16b69.jpg)

**Comment by Aculeasis** [comment]
Есть подозрительно высокие задержки между TTS say и Player, но вот эти 9 минут - MJD присылает команду с такой задержкой,  наверное что-то там с очередями.

**Comment by Garkus98** [comment]
а как увидеть эти очереди и где их найти?

**Comment by Garkus98** [comment]
Проблему исправил. В разделе терминалы в мажордомо были кучи не используемых и он им отправлял и ждал минуту прежде чем отправить тоже самое в другой. Кароче удалил весь этот мусор и голосовые терминалы начали отвечать мгновенно.
