### ISSUE TITLE
Замена snowboy

### ISSUE THREAD

**Issue by georgsp** [Aculeasis/mdmTerminal2#14]
Совсем не программист, но натолкнулся на такую вещь: https://picovoice.ai/  вроде не ресурсоемкий, работает на Python 3 (или NodeJS 10+).

**Comment by Aculeasis** [comment]
Оно есть, только версия враппера старая (хотя мб новые либы заработают) https://github.com/Aculeasis/mdmTerminal2/wiki/porcupine

Они так и не добавили поддержку arm64, так что не очень удобно тестировать. Только RBPi и некий beaglebone из одноплатников. Впрочем, надо проверить новую версию.
