### ISSUE TITLE
Подключение универсальных моделей

### ISSUE THREAD

**Issue by georgsp** [Aculeasis/mdmTerminal2#15]
А можно подключить универсальные модели типа Jarvis и.т.д ? И как это правильно сделать, подскажите пожалуйста.

**Comment by Aculeasis** [comment]
- Закинуть в `src/resources/models/` универсальную модель, например `jarvis.umdl`
- Добавить в конфиг:  ```[models] jarvis.umdl = jarvis```

Еще советуют включить ```[noise_suppression] snowboy_apply_frontend = on``` для некоторых универсальных моделей.

**Comment by Aculeasis** [comment]
[Использование универсальных моделей](https://github.com/Aculeasis/mdmTerminal2/wiki/snowboy#%D0%98%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D1%83%D0%BD%D0%B8%D0%B2%D0%B5%D1%80%D1%81%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D1%85-%D0%BC%D0%BE%D0%B4%D0%B5%D0%BB%D0%B5%D0%B9)
