### ISSUE TITLE
Объединение

### ISSUE THREAD

**Issue by devoff** [Aculeasis/mdmTerminal2#3]
Не могу найти тебя ни на форуме, ни в телеграмме. 
Мне кажется нам нужно объединить усилия над проектом, а не делать 2 отдельных, а то и народ путается, и мы одну и туже работу делаем. 

Напиши как найти тебя, спасибо

**Comment by Aculeasis** [comment]
Привет.

Мой ник на форуме [Anaki](https://majordomo.smartliving.ru/forum/memberlist.php?mode=viewprofile&u=46679), в tg [@diz0r](https://t.me/diz0r)
