### ISSUE TITLE
Отправка уведомлений на majordomo

### ISSUE THREAD

**Issue by Aculeasis** [Aculeasis/mdmTerminal2#5]
Когда терминал активируется фразой и начинает запись, когда заканчивает запись, по таймеру (пинг?).

```ini
[majordomo-notify]
object_name = 
object_method = 
# Вопрос еще в том, что именно отправлять в property.
object_property = 
# 0 - не отправлять
heartbeat_timeout = 300
```
Будет работать только если name, property и method заданы.

**Comment by skysilver-lab** [comment]
object_property на стороне терминала, пожалуй лишний, и можно его не задавать, т.к. вся отправка будет через метод.

Если  если name, и method заданы, то активировать фичу.

При вызове метода передавать в гет-запросе:
ip = IP терминала для его идентификации на стороне МДМ
status = start_record, stop_record (или как-то более узнаваемо, чтобы понимать в какое состояние перешел терминал)
uptime = системный аптайм

Как вариант еще слать уровни громкости (системной, mpd), если их не затратно получать.

**Comment by SergMicar** [comment]
Предлагаю еще добавить событие "закончил говорить"

**Comment by Aculeasis** [comment]
> ip = IP терминала для его идентификации на стороне МДМ

Почему `ip`, а не `terminal`? IP то он и так узнает, сейчас можно задать `terminal` в конфиге и он будет его передавать в запросе (системное имя терминала).
При пинге просто не передавать статус?

> Как вариант еще слать уровни громкости (системной, mpd), если их не затратно получать.

Наверное не очень, но я бы не стал. Ну или только с пингом слать.

**Comment by SergMicar** [comment]
+ события "начало воспроизведение музыки", "пауза воспроизведения музыки", "стоп воспроизведения музыки"  (majordroid API & MPD) - тогда будет полная обратная связь "команда воспроизведения музыки от МДМ" -> "Подтверждение выполнения команды"

**Comment by skysilver-lab** [comment]
> Почему ip, а не terminal? IP то он и так узнает, сейчас можно задать terminal в конфиге и он будет его передавать в запросе (системное имя терминала).
Можно и имя. Не суть. Лишь бы можно было идентифицировать (mac, id, имя и т. п.)

> При пинге просто не передавать статус?
Аха.

**Comment by netman1ac** [comment]
Предлагаю отправлять на МЖД GET'ом статусы start_talking/stop_talking  когда идет болтание терминалом функцией say/ask 
чтобы было понятно когда например ставить телевизор на муть и снимать с него ну или прикольно мигать светом в туалете :)

**Comment by SergMicar** [comment]
Поддерживаю по статусам start_talking/stop_talking
Но ставить телевизор на мут думаю нужно сразу же после распознавания ключа (например "Алиса") по событию start_record, а вот снимать с паузы можно уже по stop_talking

**Comment by SergMicar** [comment]
Итого по предложениям на сегодняшний день имеем такой перечень событий
status=
start_record
stop_record
start_talking
stop_talking
start_playmusic
stop_playmusic

volume = current volume (then changed)

uptime = timems (by heartbeat_timeout)

**Comment by netman1ac** [comment]
Видимо непонятно написал
Глушить звук со старт_записываю и до стоп_болтаю
Те и те и те статусы нужны

**Comment by Aculeasis** [comment]
Кстати,
```
object_name = 
object_method =
```
Может лучше сделать одним параметром? Все равно используется один метод и имя объекта никак не используется отдельно. Типа:

    handler = object.method

**Comment by Aculeasis** [comment]
[Отправка уведомлений на сервер MajorDoMo](https://github.com/Aculeasis/mdmTerminal2/wiki/callback)
