### ISSUE TITLE
Добавить событие speech_recognized_success

### ISSUE THREAD

**Issue by SergMicar** [Aculeasis/mdmTerminal2#6]
Добавить настройку alarmstt_recognizedsuccess, если 1 то "динг" по событию speech_recognized_success
Должно быть применимо для chrome_mode=0 и 1
Целесообразность: ответ (start_talking) после удачного распознования (особенно это заметно при chrome_mode=0) может задержатся, например происходит выборка из большой БД или просто запрос к википедии, например ))
п.с. можно будет как у гугла звуком сообщать, что фраза распознана и идет ее логический анализ (время ожидания ответа tts тогда не будет "психологически нагружено" ожиданием, т.к. мы знаем что фраза точно распознаня и она обрабатывается)
п.п.с. в гугловом голосовом поиске сейчас сделано так: "динг" по распознаванию ключа и "динг" когда закончил распознавать основной текст, а потом есть небольшая задержка пока он выведет результат поиска или озвучит его.

**Comment by Aculeasis** [comment]
> особенно это заметно при chrome_mode=0

Там был сигнал alarmkwactivated. Скорее всего ты его не слышал т.к. у апельсинки есть неприятный баг - при активации звука начало записи съедается.
Опцию `alarm_recognized` я добавлю, но сигнал будет так же не слышен в большинстве случаев.

**Comment by SergMicar** [comment]
>>Опцию alarm_recognized я добавлю, но сигнал будет так же не слышен в большинстве случаев
поэтому и прошу еще и событие speech_recognized_success (как вариант озвучивать сторонними методами по событию)

**Comment by Aculeasis** [comment]
> поэтому и прошу еще и событие speech_recognized_success (как вариант озвучивать сторонними методами по событию)

Это баг апельсинки или ее настроек и решать его нужно как баг. Например, добавить опцию `opi_sound_fix` и проигрывать 2 сигнала вместо одного там где их съедает.

**Comment by SergMicar** [comment]
событие все равно нужно, для тех, кто озвучивает (и не только) внешними средствами
